AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function for managing EC2 instances to be used as self hosted runners for Github
  Actions jobs.
Globals:
  Function:
    Timeout: 30
Parameters:
  AmiId:
    Default: ami-0e5143ec7835743eb
    Description: The AMI for the EC2 instance to be launched
    Type: String
  Ec2IamInstanceProfile:
    Default: arn:aws:iam::389640522532:instance-profile/upload_build_artifacts
    Description: The ARN of the IAM instance profile for the EC2 instance to be launched
    Type: String
  Ec2InstanceType:
    Default: c5.9xlarge
    Description: The size of the EC2 instance to be launched
    Type: String
  Ec2KeyName:
    Default: gha_runner_image_builder
    Description: The name of the key pair for the EC2 instance to be launched
    Type: String
  Ec2SecurityGroupId:
    Description: >
      The ID of the security group for the EC2 instance to be launched.
      Supply this value on the command line after obtaining it from the Terraform output.
    Type: String
  Ec2VpcSubnetId:
    Description: >
      The ID of the VPC subnet for the EC2 instance to be launched.
      Supply this value on the command line after obtaining it from the Terraform output.
    Type: String
Resources:
  ManageRunners:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 389640522532.dkr.ecr.eu-west-2.amazonaws.com/manage_runners:python3.9-v1
      Architectures:
        - x86_64
      Events:
        ManageRunners:
          Type: Api
          Properties:
            Path: /manage_runners
            Method: post
      Environment:
        Variables:
          GITHUB_APP_ID: "{{resolve:secretsmanager:gha_runner_github_app_id}}"
          GITHUB_APP_PRIVATE_KEY_BASE64: "{{resolve:secretsmanager:gha_runner_github_private_key_base64}}"
          GITHUB_APP_SECRET: "{{resolve:secretsmanager:gha_runner_github_app_secret}}"
          AMI_ID: !Sub "${AmiId}"
          EC2_IAM_INSTANCE_PROFILE: !Sub "${Ec2IamInstanceProfile}"
          EC2_INSTANCE_TYPE: !Sub "${Ec2InstanceType}"
          EC2_KEY_NAME: !Sub "${Ec2KeyName}"
          EC2_SECURITY_GROUP_ID: !Sub "${Ec2SecurityGroupId}"
          EC2_VPC_SUBNET_ID: !Sub "${Ec2VpcSubnetId}"
      Role: arn:aws:iam::389640522532:role/manage_runners

Outputs:
  ManageRunnersApi:
    Description: "API Gateway endpoint URL for Prod stage for ManageRunners function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/manage_runners/"
  ManageRunnersFunction:
    Description: "GHA runner create instance Lambda function ARN"
    Value: !GetAtt ManageRunners.Arn
